import type { Metadata } from 'next'
import Script from 'next/script';

// TailwindCSS
import './css/globals.css'

// Font And Icons 
// Supports weights 300-800
import '@fontsource-variable/open-sans';

// Font Awesome Icons 

// Main Styling 
import "./css/soft-ui-dashboard-tailwind.css?v=1.0.5"


import { Content, MenuSettings, NavBar, SideNav } from '@/components';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: '/img/favicon.png',
    apple: {
      url: 'img/apple-icon.png',
      sizes: '76x76', rel: 'apple-touch-icon'
    }

  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <body className='container-body'>
        {/* Content */}
        <Content>
          {children}
        </Content>
        <Script src="https://kit.fontawesome.com/42d5adcbca.js" strategy='lazyOnload' />
        {/* <Script src="https://unpkg.com/@popperjs/core@2" /> */}
      </body>
    </html>
  )
}
