import type { Metadata } from 'next'
import Script from 'next/script';

// TailwindCSS
import './css/globals.css'

// Font And Icons 
// Supports weights 300-800
import '@fontsource-variable/open-sans';

// Font Awesome Icons 

// Nucleo Icons 
import "./css/nucleo-icons.css"
import "./css/nucleo-svg.css"

// Main Styling 
import "./css/soft-ui-dashboard-tailwind.css?v=1.0.5"

// Script

//  plugin for scrollbar
import "./js/plugins/perfect-scrollbar.min.js"
// main script file

import { MenuSettings, NavBar, SideNav } from '@/components';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: '/img/favicon.png',
    apple: {
      url: 'img/apple-icon.png',
      sizes: '76x76', rel: 'apple-touch-icon'
    }

  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <body className='container-body'>
        {/* SideNav */}
        <SideNav />
        <main className="ease-soft-in-out xl:ml-68.5 relative h-full max-h-screen rounded-xl transition-all duration-200">
          <NavBar />
          {children}
        </main>
        <MenuSettings />
        <Script src="https://kit.fontawesome.com/42d5adcbca.js" crossOrigin="anonymous" async />
        <Script src="https://unpkg.com/@popperjs/core@2" crossOrigin="anonymous" />
        <Script async defer src="https://buttons.github.io/buttons.js" />
      </body>
    </html>
  )
}
