import type { Metadata } from 'next'

// TailwindCSS
import './css/globals.css'

// Font And Icons 
// Supports weights 300-800
import '@fontsource-variable/open-sans';

// Font Awesome Icons 

// Nucleo Icons 
import "./css/nucleo-icons.css"
import "./css/nucleo-svg.css"

// Main Styling 
import "./css/soft-ui-dashboard-tailwind.css?v=1.0.5"
import { SideNav } from '@/components';





export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: '/img/favicon.png',
    apple: {
      url: 'img/apple-icon.png',
      sizes: '76x76', rel: 'apple-touch-icon'
    }

  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <body className='container-body'>
        {/* SideNav */}
        <SideNav />
        {children}
      </body>
    </html>
  )
}
